Add files via upload
fpmBelkov/Lab_2 pull request #1
Opened 2020-09-17 15:57 UTC by fpmBelkov

2020-09-17 18:44 UTC, VeronikaYastr requested changes

2020-09-17 18:44 UTC, VeronikaYastr commented on src/main/java/com/famcs/MatrixTasks.java
> +            if (n * m <= 0) {
Лучше все-таки делать проверку n <= || m <= 0

2020-09-17 18:44 UTC, VeronikaYastr commented on src/test/java/com/famcs/MatrixTasksTests.java
> +    public static void matrixTests() {
Лучше разбить на два теста
testSwapRows, testFindDiagZeros

2020-09-21 18:14 UTC, fpmBelkov commented on src/main/java/com/famcs/MatrixTasks.java
> +            if (n * m <= 0) {
Исправил

2020-09-21 18:14 UTC, fpmBelkov commented on src/test/java/com/famcs/MatrixTasksTests.java
> +    public static void matrixTests() {
Исправил

2020-09-21 18:25 UTC, VeronikaYastr commented on src/test/java/com/famcs/TestFindDiagZeros.java
> +import org.junit.jupiter.api.Test;
Можно было в одном файле оставить)))) Просто два метода сделать и пометить их аннотацией @Test

2020-10-10 12:54 UTC, merged